language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - rbx-19mode
notifications:
  email: false
env:
  - "rack=1.2.8"
  - "rack=1.3.10"
  - "rack=1.4.5"
  - "rack=1.5.2"
  - "rack=master"
